import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import Editor from '@monaco-editor/react'
import { 
  Save, 
  Play, 
  FileText, 
  Plus, 
  Trash2, 
  Download,
  Upload,
  Zap,
  Brain,
  Sparkles
} from 'lucide-react'
import { useStore } from '../store/useStore'
import toast from 'react-hot-toast'

const Workstation = () => {
  const navigate = useNavigate()
  const {
    currentProject,
    activeFile,
    editorContent,
    setActiveFile,
    updateFileContent,
    generateCode,
    isExecuting
  } = useStore()
  
  const [aiPrompt, setAiPrompt] = useState('')
  const [showAiPanel, setShowAiPanel] = useState(false)
  const [newFileName, setNewFileName] = useState('')
  const [showNewFile, setShowNewFile] = useState(false)

  useEffect(() => {
    if (!currentProject) {
      navigate('/')
      return
    }
    
    // Auto-select first file if none selected
    if (!activeFile && currentProject.files?.length > 0) {
      setActiveFile(currentProject.files[0])
    }
  }, [currentProject, activeFile, setActiveFile, navigate])

  const handleEditorChange = (value) => {
    updateFileContent(value || '')
  }

  const handleSaveFile = () => {
    if (!activeFile) return
    
    // File is automatically saved via store
    toast.success(`Saved ${activeFile.name}`)
  }

  const handleCreateFile = () => {
    if (!newFileName.trim()) {
      toast.error('Please enter a file name')
      return
    }
    
    const newFile = {
      name: newFileName,
      content: getFileTemplate(newFileName)
    }
    
    // Add file to current project
    const updatedProject = {
      ...currentProject,
      files: [...currentProject.files, newFile],
      lastModified: 'just now'
    }
    
    // Update store (simplified for demo)
    setActiveFile(newFile)
    setNewFileName('')
    setShowNewFile(false)
    toast.success(`Created ${newFile.name}`)
  }

  const handleDeleteFile = (fileName) => {
    if (currentProject.files.length <= 1) {
      toast.error('Cannot delete the last file')
      return
    }
    
    if (window.confirm(`Delete ${fileName}?`)) {
      // Remove file logic would go here
      toast.success(`Deleted ${fileName}`)
    }
  }

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) {
      toast.error('Please enter a prompt for the AI Mechanic')
      return
    }
    
    try {
      const generatedCode = await generateCode(aiPrompt)
      updateFileContent(generatedCode)
      setAiPrompt('')
      setShowAiPanel(false)
      toast.success('Code generated by AI Mechanic!')
    } catch (error) {
      toast.error('AI Mechanic encountered an error')
    }
  }

  const getFileTemplate = (fileName) => {
    const ext = fileName.split('.').pop()?.toLowerCase()
    
    const templates = {
      'js': 'console.log("Hello from JavaScript!")\n\n// Your code here',
      'jsx': 'import React from "react"\n\nfunction Component() {\n  return (\n    <div>\n      <h1>Hello React!</h1>\n    </div>\n  )\n}\n\nexport default Component',
      'py': '#!/usr/bin/env python3\n\ndef main():\n    print("Hello from Python!")\n    # Your code here\n\nif __name__ == "__main__":\n    main()',
      'html': '<!DOCTYPE html>\n<html>\n<head>\n    <title>New Page</title>\n</head>\n<body>\n    <h1>Hello World!</h1>\n</body>\n</html>',
      'css': '/* Your styles here */\nbody {\n    font-family: Arial, sans-serif;\n    margin: 0;\n    padding: 20px;\n}',
      'json': '{\n  "name": "new-file",\n  "version": "1.0.0"\n}'
    }
    
    return templates[ext] || '// New file\n'
  }

  const getLanguage = (fileName) => {
    const ext = fileName.split('.').pop()?.toLowerCase()
    const langMap = {
      'js': 'javascript',
      'jsx': 'javascript',
      'ts': 'typescript',
      'tsx': 'typescript',
      'py': 'python',
      'html': 'html',
      'css': 'css',
      'json': 'json',
      'md': 'markdown'
    }
    return langMap[ext] || 'plaintext'
  }

  if (!currentProject) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="text-6xl mb-4">🔧</div>
          <h2 className="text-2xl font-semibold text-garage-300 mb-4">
            No Project Selected
          </h2>
          <button
            onClick={() => navigate('/')}
            className="mechanic-button"
          >
            Go to Garage
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <div className="bg-garage-900/95 backdrop-blur-sm border-b border-garage-600/30 p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <h1 className="text-2xl font-display font-bold text-oil-400">
              🔧 The Workstation
            </h1>
            <div className="text-garage-400">
              <span className="text-garage-500">Project:</span> {currentProject.name}
            </div>
          </div>
          
          <div className="flex items-center space-x-3">
            <button
              onClick={() => setShowAiPanel(true)}
              className={`
                flex items-center space-x-2 px-4 py-2 rounded-lg transition-all duration-300
                ${isExecuting 
                  ? 'bg-purple-600/20 text-purple-400 border border-purple-500/30' 
                  : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white'
                }
              `}
              disabled={isExecuting}
            >
              <Brain className={`w-4 h-4 ${isExecuting ? 'animate-pulse' : ''}`} />
              <span>{isExecuting ? 'Thinking...' : 'AI Mechanic'}</span>
            </button>
            
            <button
              onClick={handleSaveFile}
              className="oil-button flex items-center space-x-2"
              disabled={!activeFile}
            >
              <Save className="w-4 h-4" />
              <span>Save</span>
            </button>
          </div>
        </div>
      </div>

      <div className="flex-1 flex">
        {/* File Explorer */}
        <div className="w-64 bg-garage-900/50 border-r border-garage-600/30 p-4">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-garage-200">Files</h3>
            <button
              onClick={() => setShowNewFile(true)}
              className="p-1 text-garage-400 hover:text-oil-400 transition-colors"
            >
              <Plus className="w-4 h-4" />
            </button>
          </div>
          
          <div className="space-y-1">
            {currentProject.files?.map((file) => (
              <div
                key={file.name}
                className={`
                  flex items-center justify-between p-2 rounded-lg cursor-pointer transition-all duration-200
                  ${activeFile?.name === file.name 
                    ? 'bg-oil-600/20 text-oil-400 border border-oil-500/30' 
                    : 'text-garage-300 hover:bg-garage-800/50 hover:text-oil-400'
                  }
                `}
                onClick={() => setActiveFile(file)}
              >
                <div className="flex items-center space-x-2">
                  <FileText className="w-4 h-4" />
                  <span className="text-sm">{file.name}</span>
                </div>
                
                {currentProject.files.length > 1 && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      handleDeleteFile(file.name)
                    }}
                    className="opacity-0 group-hover:opacity-100 p-1 text-garage-400 hover:text-red-400 transition-all"
                  >
                    <Trash2 className="w-3 h-3" />
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Editor */}
        <div className="flex-1 flex flex-col">
          {activeFile ? (
            <>
              {/* Editor Header */}
              <div className="bg-garage-800/50 border-b border-garage-600/30 p-3 flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <FileText className="w-4 h-4 text-oil-400" />
                  <span className="font-medium text-garage-200">{activeFile.name}</span>
                  <span className="text-xs text-garage-400 bg-garage-700/50 px-2 py-1 rounded">
                    {getLanguage(activeFile.name)}
                  </span>
                </div>
                
                <div className="flex items-center space-x-2">
                  <button className="p-2 text-garage-400 hover:text-oil-400 transition-colors">
                    <Download className="w-4 h-4" />
                  </button>
                  <button className="p-2 text-garage-400 hover:text-oil-400 transition-colors">
                    <Upload className="w-4 h-4" />
                  </button>
                </div>
              </div>
              
              {/* Monaco Editor */}
              <div className="flex-1">
                <Editor
                  height="100%"
                  language={getLanguage(activeFile.name)}
                  value={editorContent}
                  onChange={handleEditorChange}
                  theme="vs-dark"
                  options={{
                    fontSize: 14,
                    fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
                    minimap: { enabled: false },
                    scrollBeyondLastLine: false,
                    automaticLayout: true,
                    tabSize: 2,
                    wordWrap: 'on'
                  }}
                />
              </div>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center">
              <div className="text-center">
                <FileText className="w-16 h-16 text-garage-500 mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-garage-300 mb-2">
                  Select a file to edit
                </h3>
                <p className="text-garage-400">
                  Choose a file from the sidebar or create a new one
                </p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* AI Mechanic Panel */}
      {showAiPanel && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="garage-card max-w-2xl w-full mx-4">
            <div className="flex items-center space-x-3 mb-4">
              <div className="p-3 bg-gradient-to-br from-purple-600 to-pink-600 rounded-lg">
                <Brain className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-garage-100">
                  AI Mechanic
                </h3>
                <p className="text-garage-400">
                  Describe what you want to build and I'll generate the code
                </p>
              </div>
            </div>
            
            <textarea
              placeholder="e.g., 'Create a React component with a counter' or 'Build a Flask API endpoint for user authentication'"
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              className="garage-input w-full h-32 mb-6 resize-none"
              autoFocus
            />
            
            <div className="flex space-x-3">
              <button
                onClick={handleAiGenerate}
                disabled={isExecuting || !aiPrompt.trim()}
                className="flex-1 mechanic-button flex items-center justify-center space-x-2"
              >
                {isExecuting ? (
                  <>
                    <Sparkles className="w-4 h-4 animate-spin" />
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <Zap className="w-4 h-4" />
                    <span>Generate Code</span>
                  </>
                )}
              </button>
              <button
                onClick={() => {
                  setShowAiPanel(false)
                  setAiPrompt('')
                }}
                className="flex-1 bg-garage-700 hover:bg-garage-600 text-garage-300 font-semibold py-3 px-6 rounded-lg transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* New File Modal */}
      {showNewFile && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="garage-card max-w-md w-full mx-4">
            <h3 className="text-xl font-semibold text-garage-100 mb-4">
              Create New File
            </h3>
            
            <input
              type="text"
              placeholder="filename.ext (e.g., app.py, style.css)"
              value={newFileName}
              onChange={(e) => setNewFileName(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleCreateFile()}
              className="garage-input w-full mb-6"
              autoFocus
            />
            
            <div className="flex space-x-3">
              <button
                onClick={handleCreateFile}
                className="flex-1 mechanic-button"
              >
                Create File
              </button>
              <button
                onClick={() => {
                  setShowNewFile(false)
                  setNewFileName('')
                }}
                className="flex-1 bg-garage-700 hover:bg-garage-600 text-garage-300 font-semibold py-3 px-6 rounded-lg transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default Workstation